import 'package:dalmia/common/app_bar.dart';
import 'package:dalmia/common/app_style.dart';
import 'package:dalmia/common/color_constant.dart';
import 'package:dalmia/common/image_constant.dart';
import 'package:dalmia/common/size_constant.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../controllers/location_wise_controller.dart';

class LocationWiseView extends GetView<LocationWiseController> {
  const LocationWiseView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Column(
        children: [
          appBar(context, title: "Reports"),
          Space.height(16),

          ///_________________________________ main menu __________________________///
          Row(
            children: [
              Space.width(16),
              Icon(
                Icons.arrow_back_ios,
                color: Colors.black,
                size: 18,
              ),
              Text(
                "Main Menu",
                style: AppStyle.textStyleInterMed(fontSize: 14),
              ),
              Spacer(),
              GestureDetector(
                onTap: () {},
                child: Container(
                  height: MySize.size40,
                  width: MySize.size150,
                  decoration: BoxDecoration(
                      color: blueColor, borderRadius: BorderRadius.circular(5)),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Image.asset(
                        ImageConstant.menu,
                        height: 15,
                        width: 19,
                      ),
                      Space.width(2),
                      Text(
                        "View other Reports",
                        style: AppStyle.textStyleInterMed(
                            fontSize: 12, color: Colors.white),
                      )
                    ],
                  ),
                ),
              ),
              Space.width(16),
            ],
          ),
          Space.height(34),

          SizedBox(
              width: MySize.size268,
              child: Column(
                children: [
                  Text(
                    "Location wise EAAI and AAAI Achieved ",
                    style: AppStyle.textStyleBoldMed(fontSize: 14),
                  ), Text(
                    " (as on <19 Oct 2023>)",
                    style: AppStyle.textStyleInterMed(fontSize: 14),
                  ),

                ],
              )),
          Space.height(14),
          tableDataAll()
        ],
      )),
    );
  }
  Widget tableDataAll() {
    return Expanded(
        child: ListView(
          scrollDirection: Axis.horizontal,
          children: [
            SingleChildScrollView(
              child: Container(
                decoration: BoxDecoration(),
                child: Padding(
                  padding: EdgeInsets.only(left: 12),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      ///________________________________________________ TITLES __________________________
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 63,
                        decoration: BoxDecoration(
                            color: Colors.blueAccent,
                            borderRadius: BorderRadius.only(
                                topRight: Radius.circular(5),
                                topLeft: Radius.circular(5))),
                        child: Row(
                          children: [
                            commonHeadingText("Details",h: 167),
                            Space.width(26),
                            commonHeadingText("DPM"),
                            Space.width(22),
                            commonHeadingText("ALR"),
                            Space.width(22),
                            commonHeadingText("BGM"),
                            Space.width(22),
                            commonHeadingText("KDP"),
                            Space.width(22),
                            commonHeadingText("CHA"),
                            commonContainer("SOUTH", Color(0xff096C9F)),
                            Space.width(22),
                            commonHeadingText("MEG"),
                            Space.width(22),
                            commonHeadingText("UGM"),
                            Space.width(22),
                            commonHeadingText("JGR"),
                            Space.width(22),
                            commonHeadingText("LAN"),
                            commonContainer("  NE  ", Color(0xff096C9F)),
                            Space.width(22),
                            commonHeadingText("CUT"),
                            Space.width(22),
                            commonHeadingText("MED"),
                            Space.width(22),
                            commonHeadingText("BOK"),
                            Space.width(22),
                            commonHeadingText("RAJ"),
                            Space.width(22),
                            commonHeadingText("KAL"),
                            commonContainer("  East  ", Color(0xff096C9F)),
                            commonContainer("cement", Color(0xff2E8CBB)),
                            Space.width(22),
                            commonHeadingText("NIG"),
                            Space.width(22),
                            commonHeadingText("RAM"),
                            Space.width(22),
                            commonHeadingText("JOW"),
                            Space.width(22),
                            commonHeadingText("NIN"),
                            Space.width(22),
                            commonHeadingText("KOL"),
                            commonContainer("SUGAR", Color(0xff2E8CBB)),
                            commonContainer("PAN IND", Color(0xff096C9F)),
                          ],
                        ),
                      ),
                      

                      ///________________________________________________ HOUSEHOLDERS LISTS __________________________
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 40,
                        child: Row(
                          children: [
                            commonHeadingText("HH Alloted", color: Colors.black,h: 167),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(25),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            commonContainer("6500", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(23),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("6500", Color(0xff096C9F)),
                            commonContainer("6500", Color(0xff2E8CBB)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(22),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer(" ", Color(0xff2E8CBB)),
                            commonContainer(" ", Color(0xff096C9F)),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 40,
                        color: Color(0xff008CD3).withOpacity(0.1),
                        child: Row(
                          children: [
                            commonHeadingText("HH Selected", color: Colors.black,h: 167),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(25),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            commonContainer("6500", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(23),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("6500", Color(0xff096C9F)),
                            commonContainer("6500", Color(0xff2E8CBB)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(22),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer(" ", Color(0xff2E8CBB)),
                            commonContainer(" ", Color(0xff096C9F)),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 102,
                        child: Row(
                          children: [
                            SizedBox(
                              width: 167,
                              child: Row(
                                children: [
                                  SizedBox(width: 75,
                                    child: Text(
                                      "No. of HHs with planned int. above 50K and 1L EAAI",
                                      style: AppStyle.textStyleInterMed(
                                          fontSize: 14, color:  Colors.black),
                                    ),
                                  ),
                                  Space.width(5),
                                  Container(height: 102,width: 1,color: Color(0xff181818).withOpacity(0.5),),
                                  Space.width(5),
                                  Column(
                                    children: [
                                      Spacer(),

                                      Text(
                                        "> Rs. 50k",
                                        style: AppStyle.textStyleInterMed(
                                            fontSize: 14, color:  Colors.black),
                                      ),
                                      Spacer(),
                                      Text(
                                        "> Rs. 1L",
                                        style: AppStyle.textStyleInterMed(
                                            fontSize: 14, color:  Colors.black),
                                      ),
                                      Spacer(),

                                    ],
                                  ),
                                ],
                              ),
                            ),
                          //  commonHeadingText("No. of HHs with planned int. above 50K and 1L EAAI", color: Colors.black,h: 167),
                         Column(crossAxisAlignment: CrossAxisAlignment.start,
                           mainAxisAlignment: MainAxisAlignment.start,
                           children: [
                           Row(children: [
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(25),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer("", Color(0xff096C9F)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             commonContainer("6500", Color(0xff096C9F)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(23),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer("6500", Color(0xff096C9F)),
                             commonContainer("6500", Color(0xff2E8CBB)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(22),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer(" ", Color(0xff2E8CBB)),
                             commonContainer(" ", Color(0xff096C9F)),
                           ],),
                           Row(children: [
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(25),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer("", Color(0xff096C9F)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             commonContainer("6500", Color(0xff096C9F)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(23),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer("6500", Color(0xff096C9F)),
                             commonContainer("6500", Color(0xff2E8CBB)),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(21),
                             commonHeadingText("6500", color: Colors.black),
                             Container(
                               height: 40,
                               width: 1,
                               color: Color(0xff181818).withOpacity(0.3),
                             ),
                             Space.width(22),
                             commonHeadingText("6500", color: Colors.black),
                             commonContainer(" ", Color(0xff2E8CBB)),
                             commonContainer(" ", Color(0xff096C9F)),
                           ],),
                         ],)
                          ],
                        ),
                      ),

                      ///________________________________________________ Interventions LISTS __________________________
/*
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 40,
                        color: Color(0xff008CD3).withOpacity(0.1),
                        child: Row(
                          children: [
                            commonHeadingText("Planned", color: Colors.black,h: 167),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(25),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            commonContainer("6500", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(23),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("6500", Color(0xff096C9F)),
                            commonContainer("6500", Color(0xff2E8CBB)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(22),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer(" ", Color(0xff2E8CBB)),
                            commonContainer(" ", Color(0xff096C9F)),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: 40,
                        child: Row(
                          children: [
                            commonHeadingText("Completed", color: Colors.black,h: 167),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(25),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            commonContainer("6500", Color(0xff096C9F)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(23),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("6500", Color(0xff096C9F)),
                            commonContainer("6500", Color(0xff2E8CBB)),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: 40,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(22),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer(" ", Color(0xff2E8CBB)),
                            commonContainer(" ", Color(0xff096C9F)),
                          ],
                        ),
                      ),
                      Container(
                        padding: EdgeInsets.only(left: 12),
                        height: MySize.size75,
                        color: Color(0xff008CD3).withOpacity(0.1),
                        child: Row(
                          children: [
                            commonHeadingText("HH with atleast 1 int. completed",
                                color: Colors.black,h: 167),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(25),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("", Color(0xff096C9F),
                                h: MySize.size75),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            commonContainer("6500", Color(0xff096C9F),
                                h: MySize.size75),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(23),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer("6500", Color(0xff096C9F),
                                h: MySize.size75),
                            commonContainer("6500", Color(0xff2E8CBB),
                                h: MySize.size75),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(21),
                            commonHeadingText("6500", color: Colors.black),
                            Container(
                              height: MySize.size75,
                              width: 1,
                              color: Color(0xff181818).withOpacity(0.3),
                            ),
                            Space.width(22),
                            commonHeadingText("6500", color: Colors.black),
                            commonContainer(" ", Color(0xff2E8CBB),
                                h: MySize.size75),
                            commonContainer(" ", Color(0xff096C9F),
                                h: MySize.size75),
                          ],
                        ),
                      ),*/

                    ],
                  ),
                ),
              ),
            ),
          ],
        ));
  }
}
